"""OpenAPI 3.0/3.1/3.2 project model (§10, §142). Model only; checks live elsewhere."""

from forge_doctor_api.analyzers.openapi.detection import Detection, detect_openapi
from forge_doctor_api.analyzers.openapi.identity import (
    normalize_method,
    normalize_path,
    operation_identity,
    path_shape,
)
from forge_doctor_api.analyzers.openapi.model import (
    OPENAPI_MODEL_SCHEMA_VERSION,
    CycleKind,
    DocumentStatus,
    IssueCode,
    OpenApiCallback,
    OpenApiDocument,
    OpenApiExtension,
    OpenApiExternalDocs,
    OpenApiIssue,
    OpenApiOperation,
    OpenApiParameter,
    OpenApiPathItem,
    OpenApiProjectModel,
    OpenApiReference,
    OpenApiRequestBody,
    OpenApiResponse,
    OpenApiSchema,
    OpenApiSchemeUse,
    OpenApiSecurityRequirement,
    OpenApiSecurityScheme,
    OpenApiServer,
    OpenApiTag,
    OpenApiWebhook,
    OperationSource,
    ReferenceCycle,
    RefStatus,
    UnresolvedExternalRef,
)
from forge_doctor_api.analyzers.openapi.parser import load_openapi_project

__all__ = [
    "OPENAPI_MODEL_SCHEMA_VERSION",
    "CycleKind",
    "Detection",
    "DocumentStatus",
    "IssueCode",
    "OpenApiCallback",
    "OpenApiDocument",
    "OpenApiExtension",
    "OpenApiExternalDocs",
    "OpenApiIssue",
    "OpenApiOperation",
    "OpenApiParameter",
    "OpenApiPathItem",
    "OpenApiProjectModel",
    "OpenApiReference",
    "OpenApiRequestBody",
    "OpenApiResponse",
    "OpenApiSchema",
    "OpenApiSchemeUse",
    "OpenApiSecurityRequirement",
    "OpenApiSecurityScheme",
    "OpenApiServer",
    "OpenApiTag",
    "OpenApiWebhook",
    "OperationSource",
    "RefStatus",
    "ReferenceCycle",
    "UnresolvedExternalRef",
    "detect_openapi",
    "load_openapi_project",
    "normalize_method",
    "normalize_path",
    "operation_identity",
    "path_shape",
]
